### ISSUE TITLE
Scroll event is propagated to window

### ISSUE THREAD

**Issue by vbocquel** [baktash93/ng2Scrollster#1]
Hi :)

I'm trying to use your lib but I'm facing an issue with it. It seems that scroll event is also propagated to the window because both the component and the window are scrolling... I guess it's not usable for now unless the entire page is not scrollable, which is not my use case.

It could be great to allow to stop the propagation, as a config option or not, it's up to you :smiley:

**Comment by baktash93** [comment]
Hi. I'll check and make a fix ASAP. Thanks for pointing it out.
